apiVersion: v1
kind: Service
metadata:
  name: webapp-deploy-svc 
  labels:
    app: webapp-deploy
spec:
  selector:
    app: webapp-deploy
  type: NodePort  
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 30513
