apiVersion: v1
kind: Service
metadata:
  name: jenkins-deployment-svc 
  labels:
    app: jenkins-server
spec:
  selector:
    app: jenkins-server
  type: NodePort  
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30512
