apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
        app: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      volumes:
      - name: Data
        persistentVolumeClaim:
          claimName: mysql-persistent-volume-data0
      containers:
      - name: mysql-deployment
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: MYSQL_USER
          value: prateek 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1"
          limits:
            memory: "4000Mi"
            cpu: "2"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: Data
          mountPath: /var/lib/mysql
