apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
        app: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - name: mysql-deployment
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin@123
        - name: MYSQL_USER
          value: prateek 
        - name: MYSQL_PASSWORD
          value: admin@123
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
        ports:
        - containerPort: 3306
