apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
        app: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - name: mysql-deployment
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret  
              key: password
        resources:
          limits:
            memory: "4000Mi"
            cpu: "2"
        ports:
        - containerPort: 3306
