apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green-app-affinity
  labels:
    application : green-app-affinity
spec:
  replica: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: green-app-affinity
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits: 
            cpu: "200m"
            memory: "200Mi"       
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:  
              - key: app
                operator: In
                values: 
                - green  