apiVersion: v1
kind: Pod
metadata:
  name: white-app-affinity
  labels:
    application: white-app-affinity
spec:
  containers:
  - name: white-app-affinity
    image: nginx
    resources:
      requests: 
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:  
          - key: app
            operator: In
            values: 
            - white   
