apiVersion: v1
kind: Pod
metadata:
  name: node-selector-example
  labels:
    name: node-selector-example
spec:
  containers:
  - name: node-selector-example
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits: 
        cpu: "2"
        memory: "1000Mi"
    ports:
      - containerPort: 80
  tolerations:
  - key: "custom-label.kubernetes.io/higucpuusages"
    operator: "Exists"
    effect: "NoSchedule"
