apiVersion: v1
kind: Pod
metadata:
  name: node-selector-example-2
  labels:
    name: node-selector-example-2
spec:
  containers:
  - name: node-selector-example-2
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits: 
        cpu: "2"
        memory: "1000Mi"
    ports:
      - containerPort: 80
  nodeSelector: 
    custom-label.kubernetes.io/app_allocate: infra