apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-persistent-volume
  labels:
    app: pgsql-deployment
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pgdata_store
    server: 172.31.12.246
