apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-persistent-volume
  labels:
    app: pgsql-deployment
annotations:
  volume.beta.kubernetes.io/storage-class: local-path
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
