apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-store-dynamic-pv
  labels:
    app: nginx-dynamic-store
annotations:
  volume.beta.kubernetes.io/storage-class: local-path
  volume.kubernetes.io/storage-provisioner: rancher.io/local-path
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-path
