apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-store-dynamic-pv
  labels:
    app: nginx-dynamic-store
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-path
