kind: Service
apiVersion: v1
metadata:
  name: mysql-data-app-svc
  namespace: mysql-data-app
  labels:
    app: mysql-data-app
spec:
  selector:
    app: mysql-data-app
  type: ClusterIP
  ports:
  - name: mysql-data-app
    port:  3306
    targetPort: 3306