apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-data-app
  namespace: mysql-data-app
spec:
  selector:
    matchLabels:
      app: mysql-data-app
  serviceName: mysql-data-app
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-data-app
    spec:
      containers:
      - name: mysql-data-app
        image: mysql:latest
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data0
          mountPath: /var/lib/mysql
      volumes:
        - name: data0
          persistentVolumeClaim:
            claimName: mysql-statefulesets-data0
